import type { Metadata } from "next";
import { Jost, Outfit } from "next/font/google";
import "@/app/globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${jost.variable}`}>
        <h1>Admin Dashboard</h1>
        {children}

        <p>Footer</p>
      </body>
    </html>
  );
}
